#!/usr/bin/env bash
# Script to configure localhost and facebook.com IPs

# Add/modify the IP for localhost
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Add/modify the IP for facebook.com
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

echo "IP addresses updated."
