#!/usr/bin/env bash
# This script modifies /etc/hosts to change localhost and facebook.com IPs

# Backup the current hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Modify the hosts file
sudo sed -i '/127.0.0.1/s/127.0.0.1/127.0.0.2/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
